import { UserRecord, InventoryItem, Location, Category, Connector, Rental, Customer, PullList } from './types';

// ============================================================================
// Mock Users - Real KG3 Team
// ============================================================================

export const mockUsers: UserRecord[] = [
  {
    id: 'user-kenny',
    googleId: 'google-kenny',
    email: 'kenny@kg3.io',
    name: 'Kenny',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Kenny&backgroundColor=10b981',
    role: 'owner',
    permissions: [],
    status: 'active',
    requestedPermissions: [],
    createdAt: '2024-01-01T00:00:00Z',
    lastLoginAt: new Date().toISOString(),
  },
  {
    id: 'user-zach',
    googleId: 'google-zach',
    email: 'zach@kg3.io',
    name: 'Zach Freeman',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=ZF&backgroundColor=3b82f6',
    role: 'manager',
    permissions: [],
    status: 'active',
    requestedPermissions: [],
    createdAt: '2024-02-01T00:00:00Z',
    lastLoginAt: new Date().toISOString(),
  },
  {
    id: 'user-nathan',
    googleId: 'google-nathan',
    email: 'nathan@kg3.io',
    name: 'Nathan Thomas',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=NT&backgroundColor=f59e0b',
    role: 'staff',
    permissions: [],
    status: 'active',
    requestedPermissions: [],
    createdAt: '2024-03-01T00:00:00Z',
    lastLoginAt: new Date().toISOString(),
  },
  {
    id: 'user-curtis',
    googleId: 'google-curtis',
    email: 'curtis@kg3.io',
    name: 'Curtis Polley',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=CP&backgroundColor=8b5cf6',
    role: 'staff',
    permissions: ['inventory.view'],
    status: 'active',
    requestedPermissions: [],
    createdAt: '2024-04-01T00:00:00Z',
    lastLoginAt: new Date().toISOString(),
  },
  {
    id: 'user-harper',
    googleId: 'google-harper',
    email: 'harper@kg3.io',
    name: 'Harper Lunn',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=HL&backgroundColor=ec4899',
    role: 'staff',
    permissions: ['inventory.view', 'rentals.view'],
    status: 'pending',
    requestedPermissions: [],
    createdAt: new Date().toISOString(),
    lastLoginAt: new Date().toISOString(),
  },
  {
    id: 'user-lily',
    googleId: 'google-lily',
    email: 'lily@kg3.io',
    name: 'Lily',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Lily&backgroundColor=06b6d4',
    role: 'staff',
    permissions: ['inventory.view', 'rentals.view'],
    status: 'active',
    requestedPermissions: ['inventory.add', 'inventory.edit'],
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    lastLoginAt: new Date().toISOString(),
  },
];

// ============================================================================
// Mock Locations
// ============================================================================

export const mockLocations: Location[] = [
  { id: 'loc-warehouse', name: 'Main Warehouse', type: 'building', parentId: null, color: '#10b981' },
  { id: 'loc-shelf-a', name: 'Shelf A - Controllers', type: 'shelf', parentId: 'loc-warehouse', color: '#3b82f6' },
  { id: 'loc-shelf-b', name: 'Shelf B - Enclosures', type: 'shelf', parentId: 'loc-warehouse', color: '#f59e0b' },
  { id: 'loc-shelf-c', name: 'Shelf C - Parts', type: 'shelf', parentId: 'loc-warehouse', color: '#8b5cf6' },
  { id: 'loc-shelf-d', name: 'Shelf D - LED Products', type: 'shelf', parentId: 'loc-warehouse', color: '#ec4899' },
  { id: 'loc-van', name: 'Van #1', type: 'vehicle', parentId: null, color: '#ef4444' },
];

// ============================================================================
// Mock Categories
// ============================================================================

export const mockCategories: Category[] = [
  { id: 'cat-controllers', name: 'Controllers', parentId: null, icon: 'Cpu', color: '#3b82f6', order: 1 },
  { id: 'cat-enclosures', name: 'Enclosures', parentId: null, icon: 'Box', color: '#10b981', order: 2 },
  { id: 'cat-connectors', name: 'Connectors', parentId: null, icon: 'Cable', color: '#f59e0b', order: 3 },
  { id: 'cat-psu', name: 'Power Supplies', parentId: null, icon: 'Zap', color: '#ef4444', order: 4 },
  { id: 'cat-plates', name: 'Plates & Panels', parentId: null, icon: 'LayoutGrid', color: '#8b5cf6', order: 5 },
  { id: 'cat-led', name: 'LED Products', parentId: null, icon: 'Lightbulb', color: '#ec4899', order: 6 },
];

// ============================================================================
// Mock Inventory Items - Real KG3 Products
// ============================================================================

export const mockInventoryItems: InventoryItem[] = [
  // Controllers
  {
    id: 'item-ctrl-a4s-mk3',
    sku: 'CTRL-A4S-MK3',
    name: 'Advatek PixLite A4-S Mk3',
    description: '4-output pixel controller, supports WS2811/WS2812/WS2813, 680 pixels per output at full refresh',
    categoryId: 'cat-controllers',
    locationId: 'loc-shelf-a',
    quantity: 12,
    availableQuantity: 10,
    unit: 'each',
    rentalRate: { amount: 285, currency: 'USD' },
    rentalPeriod: 'day',
    images: [],
    primaryImage: null,
    assignedTo: null,
    createdAt: '2024-01-15T00:00:00Z',
    createdBy: 'user-kenny',
    lastModified: new Date().toISOString(),
    lastModifiedBy: 'user-kenny',
    tags: ['pixel', 'controller', 'advatek', 'ws2812'],
    customFields: { outputs: 4, pixelsPerOutput: 680 },
    barcodes: ['CTRL-A4S-MK3-001', 'CTRL-A4S-MK3-002'],
    binCode: 'A1',
  },
  {
    id: 'item-ctrl-ledmx2max',
    sku: 'CTRL-LEDMX2MAX',
    name: 'DMXking LeDMX2 MAX',
    description: 'High-performance DMX to pixel converter, 2 universes, rack mountable',
    categoryId: 'cat-controllers',
    locationId: 'loc-shelf-a',
    quantity: 8,
    availableQuantity: 6,
    unit: 'each',
    rentalRate: { amount: 195, currency: 'USD' },
    rentalPeriod: 'day',
    images: [],
    primaryImage: null,
    assignedTo: null,
    createdAt: '2024-02-10T00:00:00Z',
    createdBy: 'user-kenny',
    lastModified: new Date().toISOString(),
    lastModifiedBy: 'user-kenny',
    tags: ['dmx', 'pixel', 'converter', 'dmxking'],
    customFields: { universes: 2 },
    barcodes: ['CTRL-LEDMX2MAX-001'],
    binCode: 'A2',
  },
  {
    id: 'item-ctrl-wled4',
    sku: 'CTRL-WLED-4',
    name: 'WLED 4-Output Controller',
    description: 'ESP32-based WLED controller with 4 pixel outputs, WiFi enabled',
    categoryId: 'cat-controllers',
    locationId: 'loc-shelf-a',
    quantity: 20,
    availableQuantity: 18,
    unit: 'each',
    rentalRate: { amount: 145, currency: 'USD' },
    rentalPeriod: 'day',
    images: [],
    primaryImage: null,
    assignedTo: null,
    createdAt: '2024-03-05T00:00:00Z',
    createdBy: 'user-kenny',
    lastModified: new Date().toISOString(),
    lastModifiedBy: 'user-zach',
    tags: ['wled', 'esp32', 'wifi', 'pixel'],
    customFields: { outputs: 4, connectivity: 'WiFi' },
    barcodes: ['CTRL-WLED-4-001', 'CTRL-WLED-4-002'],
    binCode: 'A3',
  },

  // Enclosures
  {
    id: 'item-enc-apache2800',
    sku: 'ENC-APACHE-2800',
    name: 'Apache 2800 Weatherproof Case',
    description: 'IP67 rated weatherproof case, 11.5" x 9.5" x 4.75" interior, pressure relief valve',
    categoryId: 'cat-enclosures',
    locationId: 'loc-shelf-b',
    quantity: 15,
    availableQuantity: 12,
    unit: 'each',
    rentalRate: { amount: 45, currency: 'USD' },
    rentalPeriod: 'day',
    images: [],
    primaryImage: null,
    assignedTo: null,
    createdAt: '2024-01-20T00:00:00Z',
    createdBy: 'user-kenny',
    lastModified: new Date().toISOString(),
    lastModifiedBy: 'user-kenny',
    tags: ['enclosure', 'weatherproof', 'ip67', 'apache'],
    customFields: { ipRating: 'IP67', interiorDimensions: '11.5" x 9.5" x 4.75"' },
    barcodes: ['ENC-APACHE-2800-001'],
    binCode: 'B1',
  },
  {
    id: 'item-enc-apache1800',
    sku: 'ENC-APACHE-1800',
    name: 'Apache 1800 Weatherproof Case',
    description: 'IP67 rated weatherproof case, 9.5" x 7" x 4" interior, compact form factor',
    categoryId: 'cat-enclosures',
    locationId: 'loc-shelf-b',
    quantity: 10,
    availableQuantity: 8,
    unit: 'each',
    rentalRate: { amount: 35, currency: 'USD' },
    rentalPeriod: 'day',
    images: [],
    primaryImage: null,
    assignedTo: null,
    createdAt: '2024-01-25T00:00:00Z',
    createdBy: 'user-kenny',
    lastModified: new Date().toISOString(),
    lastModifiedBy: 'user-kenny',
    tags: ['enclosure', 'weatherproof', 'ip67', 'apache', 'compact'],
    customFields: { ipRating: 'IP67', interiorDimensions: '9.5" x 7" x 4"' },
    barcodes: ['ENC-APACHE-1800-001'],
    binCode: 'B2',
  },

  // Plates
  {
    id: 'item-plate-4d1t1-l',
    sku: 'PLATE-4D-1T1',
    name: '4x D Series / 1x True1 Plate (Left)',
    description: 'CNC aluminum plate for Apache 2800, 4 D-series + 1 TRUE1 cutouts, left side',
    categoryId: 'cat-plates',
    locationId: 'loc-shelf-c',
    quantity: 25,
    availableQuantity: 22,
    unit: 'each',
    rentalRate: { amount: 14, currency: 'USD' },
    rentalPeriod: 'day',
    images: [],
    primaryImage: null,
    assignedTo: null,
    createdAt: '2024-02-01T00:00:00Z',
    createdBy: 'user-kenny',
    lastModified: new Date().toISOString(),
    lastModifiedBy: 'user-kenny',
    tags: ['plate', 'cnc', 'aluminum', 'd-series', 'true1'],
    customFields: { material: 'Aluminum', connectorSlots: 5 },
    barcodes: ['PLATE-4D-1T1-001'],
    binCode: 'C1',
  },
  {
    id: 'item-plate-2d1t1-r',
    sku: 'PLATE-2D-1T1',
    name: '2x D Series / 1x True1 Plate (Right)',
    description: 'CNC aluminum plate for Apache 2800, 2 D-series + 1 TRUE1 cutouts, right side',
    categoryId: 'cat-plates',
    locationId: 'loc-shelf-c',
    quantity: 25,
    availableQuantity: 22,
    unit: 'each',
    rentalRate: { amount: 10, currency: 'USD' },
    rentalPeriod: 'day',
    images: [],
    primaryImage: null,
    assignedTo: null,
    createdAt: '2024-02-01T00:00:00Z',
    createdBy: 'user-kenny',
    lastModified: new Date().toISOString(),
    lastModifiedBy: 'user-kenny',
    tags: ['plate', 'cnc', 'aluminum', 'd-series', 'true1'],
    customFields: { material: 'Aluminum', connectorSlots: 3 },
    barcodes: ['PLATE-2D-1T1-001'],
    binCode: 'C1',
  },
  {
    id: 'item-plate-2gang',
    sku: 'PLATE-2GANG-DECORA',
    name: '2-Gang Decora Plate',
    description: 'Standard 2-gang decora style plate, black finish',
    categoryId: 'cat-plates',
    locationId: 'loc-shelf-c',
    quantity: 50,
    availableQuantity: 45,
    unit: 'each',
    rentalRate: { amount: 8, currency: 'USD' },
    rentalPeriod: 'day',
    images: [],
    primaryImage: null,
    assignedTo: null,
    createdAt: '2024-02-15T00:00:00Z',
    createdBy: 'user-kenny',
    lastModified: new Date().toISOString(),
    lastModifiedBy: 'user-kenny',
    tags: ['plate', 'decora', '2-gang'],
    customFields: { gangs: 2, style: 'Decora' },
    barcodes: ['PLATE-2GANG-DECORA-001'],
    binCode: 'C2',
  },

  // Connectors
  {
    id: 'item-conn-nl4',
    sku: 'CONN-NL4',
    name: 'Speakon NL4 Panel Mount',
    description: 'Neutrik NL4 Speakon 4-pole panel mount connector',
    categoryId: 'cat-connectors',
    locationId: 'loc-shelf-c',
    quantity: 100,
    availableQuantity: 92,
    unit: 'each',
    rentalRate: { amount: 4.50, currency: 'USD' },
    rentalPeriod: 'day',
    images: [],
    primaryImage: null,
    assignedTo: null,
    createdAt: '2024-01-10T00:00:00Z',
    createdBy: 'user-kenny',
    lastModified: new Date().toISOString(),
    lastModifiedBy: 'user-kenny',
    tags: ['connector', 'speakon', 'nl4', 'neutrik'],
    customFields: { poles: 4, mountType: 'Panel' },
    barcodes: ['CONN-NL4-001'],
    binCode: 'C3',
  },
  {
    id: 'item-conn-true1-in',
    sku: 'CONN-PWRCON-IN',
    name: 'PowerCon TRUE1 In (Blue)',
    description: 'Neutrik TRUE1 input connector, locking AC power',
    categoryId: 'cat-connectors',
    locationId: 'loc-shelf-c',
    quantity: 60,
    availableQuantity: 55,
    unit: 'each',
    rentalRate: { amount: 7, currency: 'USD' },
    rentalPeriod: 'day',
    images: [],
    primaryImage: null,
    assignedTo: null,
    createdAt: '2024-01-10T00:00:00Z',
    createdBy: 'user-kenny',
    lastModified: new Date().toISOString(),
    lastModifiedBy: 'user-kenny',
    tags: ['connector', 'true1', 'powercon', 'neutrik', 'ac'],
    customFields: { type: 'Input', color: 'Blue' },
    barcodes: ['CONN-PWRCON-IN-001'],
    binCode: 'C4',
  },
  {
    id: 'item-conn-ethercon',
    sku: 'CONN-ETHERCON',
    name: 'Neutrik EtherCon RJ45',
    description: 'Ruggedized RJ45 panel mount connector',
    categoryId: 'cat-connectors',
    locationId: 'loc-shelf-c',
    quantity: 40,
    availableQuantity: 38,
    unit: 'each',
    rentalRate: { amount: 6, currency: 'USD' },
    rentalPeriod: 'day',
    images: [],
    primaryImage: null,
    assignedTo: null,
    createdAt: '2024-01-10T00:00:00Z',
    createdBy: 'user-kenny',
    lastModified: new Date().toISOString(),
    lastModifiedBy: 'user-kenny',
    tags: ['connector', 'ethercon', 'rj45', 'neutrik', 'ethernet'],
    customFields: { type: 'RJ45', mountType: 'Panel' },
    barcodes: ['CONN-ETHERCON-001'],
    binCode: 'C5',
  },
  {
    id: 'item-conn-xlr5f',
    sku: 'CONN-XLR5F',
    name: '5-Pin XLR Female Panel Mount',
    description: 'Neutrik NC5FD-LX 5-pin XLR female panel connector for DMX',
    categoryId: 'cat-connectors',
    locationId: 'loc-shelf-c',
    quantity: 80,
    availableQuantity: 75,
    unit: 'each',
    rentalRate: { amount: 4.50, currency: 'USD' },
    rentalPeriod: 'day',
    images: [],
    primaryImage: null,
    assignedTo: null,
    createdAt: '2024-01-10T00:00:00Z',
    createdBy: 'user-kenny',
    lastModified: new Date().toISOString(),
    lastModifiedBy: 'user-kenny',
    tags: ['connector', 'xlr', '5-pin', 'dmx', 'neutrik'],
    customFields: { pins: 5, gender: 'Female' },
    barcodes: ['CONN-XLR5F-001'],
    binCode: 'C6',
  },
  {
    id: 'item-conn-xlr3f',
    sku: 'CONN-XLR3F',
    name: '3-Pin XLR Female Panel Mount',
    description: 'Neutrik NC3FD-LX 3-pin XLR female panel connector',
    categoryId: 'cat-connectors',
    locationId: 'loc-shelf-c',
    quantity: 80,
    availableQuantity: 72,
    unit: 'each',
    rentalRate: { amount: 3.50, currency: 'USD' },
    rentalPeriod: 'day',
    images: [],
    primaryImage: null,
    assignedTo: null,
    createdAt: '2024-01-10T00:00:00Z',
    createdBy: 'user-kenny',
    lastModified: new Date().toISOString(),
    lastModifiedBy: 'user-kenny',
    tags: ['connector', 'xlr', '3-pin', 'audio', 'neutrik'],
    customFields: { pins: 3, gender: 'Female' },
    barcodes: ['CONN-XLR3F-001'],
    binCode: 'C6',
  },

  // Power Supplies
  {
    id: 'item-psu-mw-24v13a',
    sku: 'PSU-MW-24V13A',
    name: 'Meanwell 24V 13.3A PSU',
    description: 'Meanwell LRS-350-24, 320W enclosed power supply',
    categoryId: 'cat-psu',
    locationId: 'loc-shelf-c',
    quantity: 20,
    availableQuantity: 16,
    unit: 'each',
    rentalRate: { amount: 48, currency: 'USD' },
    rentalPeriod: 'day',
    images: [],
    primaryImage: null,
    assignedTo: null,
    createdAt: '2024-02-01T00:00:00Z',
    createdBy: 'user-kenny',
    lastModified: new Date().toISOString(),
    lastModifiedBy: 'user-kenny',
    tags: ['psu', 'meanwell', '24v', 'power'],
    customFields: { voltage: 24, amperage: 13.3, wattage: 320 },
    barcodes: ['PSU-MW-24V13A-001'],
    binCode: 'C7',
  },
  {
    id: 'item-psu-mw-5v10a',
    sku: 'PSU-MW-5V10A',
    name: 'Meanwell 5V 10A PSU',
    description: 'Meanwell LRS-50-5, 50W enclosed power supply for 5V LED',
    categoryId: 'cat-psu',
    locationId: 'loc-shelf-c',
    quantity: 30,
    availableQuantity: 28,
    unit: 'each',
    rentalRate: { amount: 32, currency: 'USD' },
    rentalPeriod: 'day',
    images: [],
    primaryImage: null,
    assignedTo: null,
    createdAt: '2024-02-01T00:00:00Z',
    createdBy: 'user-kenny',
    lastModified: new Date().toISOString(),
    lastModifiedBy: 'user-kenny',
    tags: ['psu', 'meanwell', '5v', 'power'],
    customFields: { voltage: 5, amperage: 10, wattage: 50 },
    barcodes: ['PSU-MW-5V10A-001'],
    binCode: 'C8',
  },
  {
    id: 'item-psu-mw-12v5a',
    sku: 'PSU-MW-12V5A',
    name: 'Meanwell 12V 5A PSU',
    description: 'Meanwell LRS-75-12, 75W enclosed power supply',
    categoryId: 'cat-psu',
    locationId: 'loc-shelf-c',
    quantity: 25,
    availableQuantity: 22,
    unit: 'each',
    rentalRate: { amount: 28, currency: 'USD' },
    rentalPeriod: 'day',
    images: [],
    primaryImage: null,
    assignedTo: null,
    createdAt: '2024-02-01T00:00:00Z',
    createdBy: 'user-kenny',
    lastModified: new Date().toISOString(),
    lastModifiedBy: 'user-kenny',
    tags: ['psu', 'meanwell', '12v', 'power'],
    customFields: { voltage: 12, amperage: 5, wattage: 75 },
    barcodes: ['PSU-MW-12V5A-001'],
    binCode: 'C9',
  },

  // LED Products
  {
    id: 'item-led-cob-warm',
    sku: 'LED-COB-3000K',
    name: 'COB LED Module 3000K Warm',
    description: 'High CRI COB LED module, 3000K warm white, 50W',
    categoryId: 'cat-led',
    locationId: 'loc-shelf-d',
    quantity: 50,
    availableQuantity: 45,
    unit: 'each',
    rentalRate: { amount: 35, currency: 'USD' },
    rentalPeriod: 'day',
    images: [],
    primaryImage: null,
    assignedTo: null,
    createdAt: '2024-03-01T00:00:00Z',
    createdBy: 'user-kenny',
    lastModified: new Date().toISOString(),
    lastModifiedBy: 'user-kenny',
    tags: ['led', 'cob', 'warm', '3000k'],
    customFields: { colorTemp: '3000K', wattage: 50, cri: 95 },
    barcodes: ['LED-COB-3000K-001'],
    binCode: 'D1',
  },
  {
    id: 'item-led-strip-ws2812',
    sku: 'LED-WS2812-60M',
    name: 'WS2812B LED Strip 60/m',
    description: 'Addressable RGB LED strip, 60 LEDs per meter, IP30',
    categoryId: 'cat-led',
    locationId: 'loc-shelf-d',
    quantity: 200,
    availableQuantity: 180,
    unit: 'meter',
    rentalRate: { amount: 12, currency: 'USD' },
    rentalPeriod: 'day',
    images: [],
    primaryImage: null,
    assignedTo: null,
    createdAt: '2024-03-01T00:00:00Z',
    createdBy: 'user-kenny',
    lastModified: new Date().toISOString(),
    lastModifiedBy: 'user-kenny',
    tags: ['led', 'strip', 'ws2812', 'pixel', 'rgb'],
    customFields: { ledsPerMeter: 60, ipRating: 'IP30', chipset: 'WS2812B' },
    barcodes: ['LED-WS2812-60M-001'],
    binCode: 'D2',
  },
  {
    id: 'item-led-strip-sk6812',
    sku: 'LED-SK6812-RGBW',
    name: 'SK6812 RGBW LED Strip 60/m',
    description: 'Addressable RGBW LED strip, 60 LEDs per meter, IP65 silicone sleeve',
    categoryId: 'cat-led',
    locationId: 'loc-shelf-d',
    quantity: 150,
    availableQuantity: 140,
    unit: 'meter',
    rentalRate: { amount: 18, currency: 'USD' },
    rentalPeriod: 'day',
    images: [],
    primaryImage: null,
    assignedTo: null,
    createdAt: '2024-03-01T00:00:00Z',
    createdBy: 'user-kenny',
    lastModified: new Date().toISOString(),
    lastModifiedBy: 'user-kenny',
    tags: ['led', 'strip', 'sk6812', 'pixel', 'rgbw'],
    customFields: { ledsPerMeter: 60, ipRating: 'IP65', chipset: 'SK6812' },
    barcodes: ['LED-SK6812-RGBW-001'],
    binCode: 'D3',
  },

  // Built Controller Boxes
  {
    id: 'item-box-pxl4out-std',
    sku: 'PXL-4OUT-STD',
    name: 'KG3 PixLite 4-Output Control Box',
    description: 'Complete 4-output pixel controller in Apache 2800 case, A4-S Mk3, 24V PSU, weatherproof',
    categoryId: 'cat-controllers',
    locationId: 'loc-shelf-a',
    quantity: 5,
    availableQuantity: 3,
    unit: 'each',
    rentalRate: { amount: 150, currency: 'USD' },
    rentalPeriod: 'day',
    images: [],
    primaryImage: null,
    assignedTo: null,
    createdAt: '2024-04-01T00:00:00Z',
    createdBy: 'user-kenny',
    lastModified: new Date().toISOString(),
    lastModifiedBy: 'user-kenny',
    tags: ['controller', 'box', 'pixel', 'complete', 'weatherproof'],
    customFields: { outputs: 4, controller: 'A4-S Mk3', enclosure: 'Apache 2800' },
    barcodes: ['PXL-4OUT-STD-001', 'PXL-4OUT-STD-002'],
    binCode: 'A4',
  },
  {
    id: 'item-box-wled4out-bud',
    sku: 'WLED-4OUT-BUD',
    name: 'KG3 WLED 4-Output Budget Controller',
    description: 'Budget 4-output WLED controller in Apache 1800, 5V PSU, WiFi enabled',
    categoryId: 'cat-controllers',
    locationId: 'loc-shelf-a',
    quantity: 8,
    availableQuantity: 6,
    unit: 'each',
    rentalRate: { amount: 85, currency: 'USD' },
    rentalPeriod: 'day',
    images: [],
    primaryImage: null,
    assignedTo: null,
    createdAt: '2024-04-15T00:00:00Z',
    createdBy: 'user-zach',
    lastModified: new Date().toISOString(),
    lastModifiedBy: 'user-zach',
    tags: ['controller', 'box', 'wled', 'budget', 'wifi'],
    customFields: { outputs: 4, controller: 'WLED ESP32', enclosure: 'Apache 1800' },
    barcodes: ['WLED-4OUT-BUD-001'],
    binCode: 'A5',
  },
];

// ============================================================================
// Mock Connectors (8 types)
// ============================================================================

export const mockConnectors: Connector[] = [
  {
    id: 'conn-xlr-male-3',
    name: 'XLR Male 3-Pin',
    type: 'xlr',
    manufacturer: 'Neutrik',
    partNumber: 'NC3MXX',
    pins: [
      { id: 'pin1', number: 1, label: 'Ground', function: 'Shield/Ground', color: '#1a1a1a', position: { x: 100, y: 150 } },
      { id: 'pin2', number: 2, label: 'Hot (+)', function: 'Signal Hot', color: '#ef4444', position: { x: 80, y: 100 } },
      { id: 'pin3', number: 3, label: 'Cold (-)', function: 'Signal Cold', color: '#f5f5f5', position: { x: 120, y: 100 } },
    ],
    diagramSvg: '',
    thumbnailUrl: '',
    category: 'audio',
    tags: ['xlr', 'balanced', 'audio', '3-pin'],
  },
  {
    id: 'conn-xlr-female-3',
    name: 'XLR Female 3-Pin',
    type: 'xlr',
    manufacturer: 'Neutrik',
    partNumber: 'NC3FXX',
    pins: [
      { id: 'pin1', number: 1, label: 'Ground', function: 'Shield/Ground', color: '#1a1a1a', position: { x: 100, y: 150 } },
      { id: 'pin2', number: 2, label: 'Hot (+)', function: 'Signal Hot', color: '#ef4444', position: { x: 120, y: 100 } },
      { id: 'pin3', number: 3, label: 'Cold (-)', function: 'Signal Cold', color: '#f5f5f5', position: { x: 80, y: 100 } },
    ],
    diagramSvg: '',
    thumbnailUrl: '',
    category: 'audio',
    tags: ['xlr', 'balanced', 'audio', '3-pin'],
  },
  {
    id: 'conn-dmx-5pin',
    name: 'DMX 5-Pin',
    type: 'dmx',
    manufacturer: 'Neutrik',
    partNumber: 'NC5MXX',
    pins: [
      { id: 'pin1', number: 1, label: 'Ground', function: 'Shield/Ground', color: '#1a1a1a', position: { x: 100, y: 160 } },
      { id: 'pin2', number: 2, label: 'Data 1-', function: 'Data 1 Cold', color: '#3b82f6', position: { x: 70, y: 120 } },
      { id: 'pin3', number: 3, label: 'Data 1+', function: 'Data 1 Hot', color: '#ef4444', position: { x: 90, y: 80 } },
      { id: 'pin4', number: 4, label: 'Data 2-', function: 'Data 2 Cold', color: '#22c55e', position: { x: 110, y: 80 } },
      { id: 'pin5', number: 5, label: 'Data 2+', function: 'Data 2 Hot', color: '#f5f5f5', position: { x: 130, y: 120 } },
    ],
    diagramSvg: '',
    thumbnailUrl: '',
    category: 'lighting',
    tags: ['dmx', 'lighting', 'control', '5-pin'],
  },
  {
    id: 'conn-phoenix-5',
    name: 'Phoenix 5-Pin Terminal',
    type: 'phoenix',
    manufacturer: 'Phoenix Contact',
    partNumber: 'MSTB 2.5',
    pins: [
      { id: 'term1', number: 1, label: 'Terminal 1', function: 'Configurable', color: null, position: { x: 20, y: 50 } },
      { id: 'term2', number: 2, label: 'Terminal 2', function: 'Configurable', color: null, position: { x: 50, y: 50 } },
      { id: 'term3', number: 3, label: 'Terminal 3', function: 'Configurable', color: null, position: { x: 80, y: 50 } },
      { id: 'term4', number: 4, label: 'Terminal 4', function: 'Configurable', color: null, position: { x: 110, y: 50 } },
      { id: 'term5', number: 5, label: 'Terminal 5', function: 'Configurable', color: null, position: { x: 140, y: 50 } },
    ],
    diagramSvg: '',
    thumbnailUrl: '',
    category: 'data',
    tags: ['phoenix', 'terminal', 'screw'],
  },
  {
    id: 'conn-rj45',
    name: 'RJ45 Ethernet',
    type: 'rj45',
    manufacturer: null,
    partNumber: null,
    pins: [
      { id: 'pin1', number: 1, label: 'TX+', function: 'Transmit +', color: '#f97316', position: { x: 20, y: 30 } },
      { id: 'pin2', number: 2, label: 'TX-', function: 'Transmit -', color: '#f97316', position: { x: 35, y: 30 } },
      { id: 'pin3', number: 3, label: 'RX+', function: 'Receive +', color: '#22c55e', position: { x: 50, y: 30 } },
      { id: 'pin4', number: 4, label: 'NC', function: 'Not Used', color: '#3b82f6', position: { x: 65, y: 30 } },
      { id: 'pin5', number: 5, label: 'NC', function: 'Not Used', color: '#3b82f6', position: { x: 80, y: 30 } },
      { id: 'pin6', number: 6, label: 'RX-', function: 'Receive -', color: '#22c55e', position: { x: 95, y: 30 } },
      { id: 'pin7', number: 7, label: 'NC', function: 'Not Used', color: '#78350f', position: { x: 110, y: 30 } },
      { id: 'pin8', number: 8, label: 'NC', function: 'Not Used', color: '#78350f', position: { x: 125, y: 30 } },
    ],
    diagramSvg: '',
    thumbnailUrl: '',
    category: 'data',
    tags: ['rj45', 'ethernet', 'network', 'cat6'],
  },
  {
    id: 'conn-powercon-blue',
    name: 'PowerCon Blue (Input)',
    type: 'powercon',
    manufacturer: 'Neutrik',
    partNumber: 'NAC3FCA',
    pins: [
      { id: 'pin-n', number: 'N', label: 'Neutral', function: 'AC Neutral', color: '#3b82f6', position: { x: 80, y: 100 } },
      { id: 'pin-l', number: 'L', label: 'Line', function: 'AC Line', color: '#78350f', position: { x: 120, y: 100 } },
      { id: 'pin-e', number: 'E', label: 'Earth', function: 'Ground', color: '#22c55e', position: { x: 100, y: 140 } },
    ],
    diagramSvg: '',
    thumbnailUrl: '',
    category: 'power',
    tags: ['powercon', 'power', 'ac', 'input'],
  },
  {
    id: 'conn-powercon-gray',
    name: 'PowerCon Gray (Output)',
    type: 'powercon',
    manufacturer: 'Neutrik',
    partNumber: 'NAC3FCB',
    pins: [
      { id: 'pin-n', number: 'N', label: 'Neutral', function: 'AC Neutral', color: '#3b82f6', position: { x: 80, y: 100 } },
      { id: 'pin-l', number: 'L', label: 'Line', function: 'AC Line', color: '#78350f', position: { x: 120, y: 100 } },
      { id: 'pin-e', number: 'E', label: 'Earth', function: 'Ground', color: '#22c55e', position: { x: 100, y: 140 } },
    ],
    diagramSvg: '',
    thumbnailUrl: '',
    category: 'power',
    tags: ['powercon', 'power', 'ac', 'output'],
  },
  {
    id: 'conn-ethercon',
    name: 'EtherCon',
    type: 'ethercon',
    manufacturer: 'Neutrik',
    partNumber: 'NE8MX',
    pins: [
      { id: 'pin1', number: 1, label: 'TX+', function: 'Transmit +', color: '#f97316', position: { x: 20, y: 30 } },
      { id: 'pin2', number: 2, label: 'TX-', function: 'Transmit -', color: '#f97316', position: { x: 35, y: 30 } },
      { id: 'pin3', number: 3, label: 'RX+', function: 'Receive +', color: '#22c55e', position: { x: 50, y: 30 } },
      { id: 'pin4', number: 4, label: 'NC', function: 'Not Used', color: '#3b82f6', position: { x: 65, y: 30 } },
      { id: 'pin5', number: 5, label: 'NC', function: 'Not Used', color: '#3b82f6', position: { x: 80, y: 30 } },
      { id: 'pin6', number: 6, label: 'RX-', function: 'Receive -', color: '#22c55e', position: { x: 95, y: 30 } },
      { id: 'pin7', number: 7, label: 'NC', function: 'Not Used', color: '#78350f', position: { x: 110, y: 30 } },
      { id: 'pin8', number: 8, label: 'NC', function: 'Not Used', color: '#78350f', position: { x: 125, y: 30 } },
    ],
    diagramSvg: '',
    thumbnailUrl: '',
    category: 'data',
    tags: ['ethercon', 'ethernet', 'network', 'rugged'],
  },
];

// ============================================================================
// Mock Rentals - Real KG3 Customers
// ============================================================================

const today = new Date();
const dayMs = 24 * 60 * 60 * 1000;

export const mockRentals: Rental[] = [
  {
    id: 'rental-1',
    customerName: 'Tyler Childers Tour',
    customerEmail: 'production@tylerchilders.com',
    customerPhone: '615-555-0100',
    startDate: new Date(today.getTime() + 2 * dayMs).toISOString().split('T')[0],
    endDate: new Date(today.getTime() + 14 * dayMs).toISOString().split('T')[0],
    actualReturnDate: null,
    items: [
      { itemId: 'item-box-pxl4out-std', quantity: 4, rate: { amount: 150, currency: 'USD' }, subtotal: { amount: 1800, currency: 'USD' } },
      { itemId: 'item-led-strip-sk6812', quantity: 100, rate: { amount: 18, currency: 'USD' }, subtotal: { amount: 1800, currency: 'USD' } },
    ],
    totalCost: { amount: 3600, currency: 'USD' },
    depositAmount: { amount: 1500, currency: 'USD' },
    depositReturned: false,
    paymentStatus: 'partial',
    status: 'reserved',
    notes: 'Tour dates - Nashville to Austin',
    internalNotes: 'VIP - Direct from management',
    createdAt: new Date(today.getTime() - 5 * dayMs).toISOString(),
    createdBy: 'user-kenny',
    lastModified: new Date().toISOString(),
    lastModifiedBy: 'user-kenny',
  },
  {
    id: 'rental-2',
    customerName: 'Brett Eldredge Productions',
    customerEmail: 'av@bretteldredge.com',
    customerPhone: '615-555-0200',
    startDate: new Date(today.getTime() - 1 * dayMs).toISOString().split('T')[0],
    endDate: new Date(today.getTime() + 3 * dayMs).toISOString().split('T')[0],
    actualReturnDate: null,
    items: [
      { itemId: 'item-box-wled4out-bud', quantity: 6, rate: { amount: 85, currency: 'USD' }, subtotal: { amount: 510, currency: 'USD' } },
      { itemId: 'item-led-strip-ws2812', quantity: 50, rate: { amount: 12, currency: 'USD' }, subtotal: { amount: 600, currency: 'USD' } },
    ],
    totalCost: { amount: 1110, currency: 'USD' },
    depositAmount: { amount: 500, currency: 'USD' },
    depositReturned: false,
    paymentStatus: 'paid',
    status: 'active',
    notes: 'Christmas special performance',
    internalNotes: null,
    createdAt: new Date(today.getTime() - 7 * dayMs).toISOString(),
    createdBy: 'user-zach',
    lastModified: new Date().toISOString(),
    lastModifiedBy: 'user-zach',
  },
  {
    id: 'rental-3',
    customerName: 'Red Bull Events',
    customerEmail: 'events@redbull.com',
    customerPhone: '310-555-0300',
    startDate: new Date(today.getTime() + 7 * dayMs).toISOString().split('T')[0],
    endDate: new Date(today.getTime() + 10 * dayMs).toISOString().split('T')[0],
    actualReturnDate: null,
    items: [
      { itemId: 'item-ctrl-a4s-mk3', quantity: 8, rate: { amount: 285, currency: 'USD' }, subtotal: { amount: 2280, currency: 'USD' } },
      { itemId: 'item-led-cob-warm', quantity: 20, rate: { amount: 35, currency: 'USD' }, subtotal: { amount: 700, currency: 'USD' } },
    ],
    totalCost: { amount: 2980, currency: 'USD' },
    depositAmount: { amount: 1000, currency: 'USD' },
    depositReturned: false,
    paymentStatus: 'unpaid',
    status: 'reserved',
    notes: 'Extreme sports event activation',
    internalNotes: 'Corporate account - NET 30',
    createdAt: new Date(today.getTime() - 3 * dayMs).toISOString(),
    createdBy: 'user-kenny',
    lastModified: new Date().toISOString(),
    lastModifiedBy: 'user-kenny',
  },
  {
    id: 'rental-4',
    customerName: 'YouVersion Church',
    customerEmail: 'av@youversion.com',
    customerPhone: '405-555-0400',
    startDate: new Date(today.getTime() - 5 * dayMs).toISOString().split('T')[0],
    endDate: new Date(today.getTime() - 2 * dayMs).toISOString().split('T')[0],
    actualReturnDate: null,
    items: [
      { itemId: 'item-ctrl-ledmx2max', quantity: 4, rate: { amount: 195, currency: 'USD' }, subtotal: { amount: 780, currency: 'USD' } },
    ],
    totalCost: { amount: 780, currency: 'USD' },
    depositAmount: { amount: 300, currency: 'USD' },
    depositReturned: false,
    paymentStatus: 'overdue',
    status: 'overdue',
    notes: 'Easter service production',
    internalNotes: 'Follow up on return',
    createdAt: new Date(today.getTime() - 10 * dayMs).toISOString(),
    createdBy: 'user-nathan',
    lastModified: new Date().toISOString(),
    lastModifiedBy: 'user-kenny',
  },
  {
    id: 'rental-5',
    customerName: 'Lake Street Dive',
    customerEmail: 'tour@lakestreetdive.com',
    customerPhone: '617-555-0500',
    startDate: new Date(today.getTime() + 20 * dayMs).toISOString().split('T')[0],
    endDate: new Date(today.getTime() + 35 * dayMs).toISOString().split('T')[0],
    actualReturnDate: null,
    items: [
      { itemId: 'item-box-pxl4out-std', quantity: 2, rate: { amount: 150, currency: 'USD' }, subtotal: { amount: 300, currency: 'USD' } },
      { itemId: 'item-led-strip-sk6812', quantity: 80, rate: { amount: 18, currency: 'USD' }, subtotal: { amount: 1440, currency: 'USD' } },
    ],
    totalCost: { amount: 1740, currency: 'USD' },
    depositAmount: { amount: 800, currency: 'USD' },
    depositReturned: false,
    paymentStatus: 'unpaid',
    status: 'draft',
    notes: 'Summer tour dates',
    internalNotes: null,
    createdAt: new Date().toISOString(),
    createdBy: 'user-zach',
    lastModified: new Date().toISOString(),
    lastModifiedBy: 'user-zach',
  },
];

// ============================================================================
// Mock Customers - Real KG3 Clients
// ============================================================================

export const mockCustomers: Customer[] = [
  {
    id: 'cust-1',
    name: 'Tyler Childers Tour',
    email: 'production@tylerchilders.com',
    phone: '615-555-0100',
    company: 'Hickman Holler Productions',
    notes: 'VIP - Long-term touring client',
    createdAt: '2024-01-15T00:00:00Z',
    lastRentalDate: new Date(today.getTime() - 5 * dayMs).toISOString(),
  },
  {
    id: 'cust-2',
    name: 'Brett Eldredge Productions',
    email: 'av@bretteldredge.com',
    phone: '615-555-0200',
    company: 'BE Productions LLC',
    notes: 'Christmas shows specialist',
    createdAt: '2024-02-20T00:00:00Z',
    lastRentalDate: new Date(today.getTime() - 1 * dayMs).toISOString(),
  },
  {
    id: 'cust-3',
    name: 'Red Bull Events',
    email: 'events@redbull.com',
    phone: '310-555-0300',
    company: 'Red Bull North America',
    notes: 'Corporate account - NET 30 terms',
    createdAt: '2024-03-10T00:00:00Z',
    lastRentalDate: new Date(today.getTime() - 30 * dayMs).toISOString(),
  },
  {
    id: 'cust-4',
    name: 'YouVersion Church',
    email: 'av@youversion.com',
    phone: '405-555-0400',
    company: 'Life.Church',
    notes: 'Major holiday productions, budget-conscious',
    createdAt: '2024-04-05T00:00:00Z',
    lastRentalDate: new Date(today.getTime() - 5 * dayMs).toISOString(),
  },
  {
    id: 'cust-5',
    name: 'Lake Street Dive',
    email: 'tour@lakestreetdive.com',
    phone: '617-555-0500',
    company: 'LSD Touring Inc',
    notes: 'Summer tours, eco-friendly LED requests',
    createdAt: '2024-05-01T00:00:00Z',
  },
];

// ============================================================================
// Mock Pull Lists
// ============================================================================

export const mockPullLists: PullList[] = [
  {
    id: 'pull-1',
    rentalId: 'rental-1',
    status: 'ready',
    createdBy: 'user-zach',
    createdAt: new Date(today.getTime() - 3 * dayMs).toISOString(),
    items: [
      {
        sku: 'PXL-4OUT-STD',
        itemId: 'item-box-pxl4out-std',
        itemName: 'KG3 PixLite 4-Output Control Box',
        quantityNeeded: 4,
        quantityPulled: 0,
        binLocation: 'A4',
      },
      {
        sku: 'LED-SK6812-RGBW',
        itemId: 'item-led-strip-sk6812',
        itemName: 'SK6812 RGBW LED Strip 60/m',
        quantityNeeded: 100,
        quantityPulled: 0,
        binLocation: 'D3',
      },
    ],
    notes: 'Tyler Childers Tour - Nashville to Austin',
    assignedTo: 'user-nathan',
  },
  {
    id: 'pull-2',
    rentalId: 'rental-2',
    status: 'in-progress',
    createdBy: 'user-zach',
    createdAt: new Date(today.getTime() - 2 * dayMs).toISOString(),
    startedAt: new Date(today.getTime() - 1 * dayMs).toISOString(),
    items: [
      {
        sku: 'WLED-4OUT-BUD',
        itemId: 'item-box-wled4out-bud',
        itemName: 'KG3 WLED 4-Output Budget Controller',
        quantityNeeded: 6,
        quantityPulled: 4,
        pulledBy: 'user-nathan',
        pulledAt: new Date(today.getTime() - 1 * dayMs).toISOString(),
        binLocation: 'A5',
      },
      {
        sku: 'LED-WS2812-60M',
        itemId: 'item-led-strip-ws2812',
        itemName: 'WS2812B LED Strip 60/m',
        quantityNeeded: 50,
        quantityPulled: 50,
        pulledBy: 'user-nathan',
        pulledAt: new Date(today.getTime() - 1 * dayMs).toISOString(),
        binLocation: 'D2',
      },
    ],
    notes: 'Brett Eldredge Christmas special',
    assignedTo: 'user-nathan',
  },
  {
    id: 'pull-3',
    rentalId: 'rental-3',
    status: 'draft',
    createdBy: 'user-kenny',
    createdAt: new Date(today.getTime() - 1 * dayMs).toISOString(),
    items: [
      {
        sku: 'CTRL-A4S-MK3',
        itemId: 'item-ctrl-a4s-mk3',
        itemName: 'Advatek PixLite A4-S Mk3',
        quantityNeeded: 8,
        quantityPulled: 0,
        binLocation: 'A1',
      },
      {
        sku: 'LED-COB-3000K',
        itemId: 'item-led-cob-warm',
        itemName: 'COB LED Module 3000K Warm',
        quantityNeeded: 20,
        quantityPulled: 0,
        binLocation: 'D1',
      },
    ],
    notes: 'Red Bull Events activation',
    assignedTo: undefined,
  },
];
